### PR TITLE
add header content-type automatically for serialized annotation

### PR DESCRIPTION
**Pull request by jaumard**
With this I'm able to send and received protobuf data !!! :D

### CODE REVIEW

**Comment by jaumard** [comment]
Thanks :) could you publish also proto serializer ?

**Comment by tejainece** [comment]
Could you move the project into jaguar_serializer repository?

**Comment by jaumard** [comment]
if you want yes

**Comment by jaumard** [comment]
i let you delete the repo I don't have the rights

**Comment by tejainece** [comment]
I will delete it later, when it has been pulled into the serializer repo.

**Pull request merged**
